name: Deploy Annual Leave Calculator Lambda

on:
  push:
    branches:
      - main

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'gradle'

      - name: Make Gradle wrapper executable
        run: cd leavecalc && chmod +x ./gradlew

      - name: Run Test
        run: cd leavecalc && ./gradlew test

      - name: Build with Gradle
        run: cd leavecalc && ./gradlew build -x test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to Lambda with SnapStart
        run: |
          JAR_PATH="build/libs/leavecalc.jar"
          
          VERSION=$(aws lambda update-function-code \
          --function-name annualLeaveCalculator \
          --zip-file fileb://${JAR_PATH} \
          --query 'Version' --output text)
          
          echo "새 버전 배포됨: $VERSION"
          
          aws lambda put-function-configuration \
          --function-name annualLeaveCalculator \
          --snap-start ApplyOn=PublishedVersions
          
          aws lambda update-alias \
          --function-name annualLeaveCalculator \
          --name prod \
          --function-version $VERSION

      - name: Verify Deployment
        run: |
          aws lambda get-function \
          --function-name annualLeaveCalculator:prod \
          --query 'Configuration.[State,LastUpdateStatus]'
          
          aws lambda invoke \
          --function-name annualLeaveCalculator:prod \
          --payload '{"action": "test"}' \
          response.json

          cat response.json
