name: Deploy Annual Leave Calculator Lambda

on:
  push:
    branches:
      - main

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'gradle'

      - name: Make Gradle wrapper executable
        run: cd leavecalc && chmod +x ./gradlew

      - name: Run Test
        run: cd leavecalc && ./gradlew test

      - name: Build with Gradle
        run: cd leavecalc && ./gradlew build -x test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to Lambda with SnapStart
        run: |
          JAR_PATH="leavecalc/build/libs/leavecalc.jar"
          
          aws lambda update-function-code \
          --function-name annualLeaveCalculator \
          --zip-file fileb://${JAR_PATH}
          
          echo "코드 업로드 완료, 업데이트가 적용될 때까지 대기 중..."
          
          while true; do
            STATUS=$(aws lambda get-function \
            --function-name annualLeaveCalculator \
            --query 'Configuration.LastUpdateStatus' \
            --output text)
          
            if [ "$STATUS" = "Successful" ]; then
              echo "코드 업데이트 완료!"
              break
            fi
            echo "현재 상태: $STATUS, 5초 후 다시 확인..."
            sleep 5
          done
          
          aws lambda update-function-configuration \
          --function-name annualLeaveCalculator \
          --snap-start ApplyOn=PublishedVersions
          
           echo "SnapStart 설정 완료, 설정이 적용될 때까지 대기 중..."
          
          # 설정 업데이트 완료 대기
          while true; do
            STATUS=$(aws lambda get-function \
            --function-name annualLeaveCalculator \
            --query 'Configuration.LastUpdateStatus' \
            --output text)
          
            if [ "$STATUS" = "Successful" ]; then
              echo "SnapStart 설정 업데이트 완료!"
              break
            fi
            echo "현재 상태: $STATUS, 5초 후 다시 확인..."
            sleep 5
          done
          
           VERSION=$(aws lambda publish-version \
          --function-name annualLeaveCalculator \
          --description "Deployed via GitHub Actions on $(date)" \
          --query 'Version' --output text)
          
          echo "새 버전 게시됨: $VERSION"
          
          aws lambda update-alias \
          --function-name annualLeaveCalculator \
          --name prod \
          --function-version $VERSION

      - name: Verify Deployment
        run: |
          aws lambda get-function \
          --function-name annualLeaveCalculator:prod \
          --query 'Configuration.[State,LastUpdateStatus]'
          
          aws lambda invoke \
          --cli-binary-format raw-in-base64-out \
          --function-name annualLeaveCalculator:prod \
          --payload '{"action": "test"}' \
          response.json

          cat response.json
